"""
tests/test_graph2_services.py
------------------------------
Unit tests for LLMService and Graph 2 modular services:
    - LLMService (mandatory API key enforcement)
    - ContextBuilderService
    - EvidenceCollectorService
    - DecisionPlanningService
    - RiskAssessmentService
    - MitigationPlanningService
    - ReflectionService
    - RiskReportBuilderService
"""

import pytest
from exceptions import LLMConfigurationError
from workflow.workflow_service import WorkflowService
from intelligence.engine import get_intelligence_engine
from rag.rag_retrieval_service import RAGRetrievalService
from services.llm_service import LLMService
from services import (
    ContextBuilderService,
    EvidenceCollectorService,
    DecisionPlanningService,
    RiskAssessmentService,
    MitigationPlanningService,
    ReflectionService,
    RiskReportBuilderService,
)
from services.decision_planning_service import DecisionPlanOutput
from services.risk_assessment_service import RiskAssessmentOutput
from services.mitigation_planning_service import MitigationPlanningOutput
from schemas.domain import (
    EvidenceItem,
    CategorizedRisk,
    MitigationPlan,
    ReflectionFeedback,
    RiskAssessmentReport,
)


class MockLLMService(LLMService):
    """Mock LLMService for offline test suites."""

    def __init__(self):
        self.provider = "openai"
        self.api_key = "sk-test-mock-key"
        self.model_name = "gpt-4o-mini"

    def validate_configuration(self) -> None:
        pass

    def invoke_text(self, prompt: str) -> str:
        return "Executive summary generated by Mock LLM for project analysis."

    def invoke_structured(self, prompt: str, response_model: type):
        if response_model.__name__ == "DecisionPlanOutput":
            return DecisionPlanOutput(priorities=["Unblock vendor deliverables", "Mitigate critical risks"])
        elif response_model.__name__ == "RiskAssessmentOutput":
            return RiskAssessmentOutput(
                risks=[
                    CategorizedRisk(
                        risk_id="risk_llm_1",
                        category="vendor_delivery",
                        title="CloudSphere Vendor Delay",
                        description="API Gateway delivery missed by vendor.",
                        probability="high",
                        impact="critical",
                        risk_score=90.0,
                    )
                ]
            )
        elif response_model.__name__ == "MitigationPlanningOutput":
            return MitigationPlanningOutput(
                mitigations=[
                    MitigationPlan(
                        mitigation_id="mit_llm_1",
                        target_risk_id="risk_llm_1",
                        action_title="Invoke Vendor SLA Penalties",
                        action_description="Formal executive escalation.",
                        owner="Program Manager",
                        due_date="2026-08-31",
                        cost_estimate="Low",
                        expected_impact="High Risk Reduction",
                    )
                ]
            )
        elif response_model.__name__ == "ReflectionFeedback":
            if "FORCE_REFLECTION_RETRY" in prompt:
                return ReflectionFeedback(
                    passed=False,
                    grounding_score=0.5,
                    consistency_score=0.5,
                    unsupported_claims=["Forced retry claim"],
                    reflection_notes="Audit failed — retry needed.",
                )
            return ReflectionFeedback(
                passed=True,
                grounding_score=0.95,
                consistency_score=0.95,
                unsupported_claims=[],
                reflection_notes="Grounded by LLM audit.",
            )
        return response_model()


@pytest.fixture
def mock_llm():
    return MockLLMService()


@pytest.fixture
def intelligence_alpha():
    """Generate ProjectIntelligence for Project 1 (Alpha)."""
    bundle = WorkflowService().run_graph1(1)
    return get_intelligence_engine().analyze(bundle)


class TestLLMServiceValidation:

    def test_missing_api_key_raises_llm_configuration_error(self):
        with pytest.raises(LLMConfigurationError) as exc_info:
            LLMService(provider="openai", api_key="")
        assert "LLM_API_KEY" in str(exc_info.value)

    def test_placeholder_api_key_raises_llm_configuration_error(self):
        with pytest.raises(LLMConfigurationError) as exc_info:
            LLMService(provider="openai", api_key="placeholder")
        assert "LLM_API_KEY" in str(exc_info.value)


class TestRAGRetrievalService:

    def test_search_returns_evidence_items(self, intelligence_alpha):
        rag_service = RAGRetrievalService()
        evidence = rag_service.search("1", "vendor delivery delay spheres", top_k=3)
        assert isinstance(evidence, list)
        assert len(evidence) > 0
        assert all(isinstance(e, EvidenceItem) for e in evidence)


class TestContextBuilderService:

    def test_build_context_returns_summary_string(self, intelligence_alpha, mock_llm):
        service = ContextBuilderService(llm_service=mock_llm)
        summary = service.build_context(intelligence_alpha)
        assert isinstance(summary, str)
        assert len(summary) > 0


class TestEvidenceCollectorService:

    def test_collect_evidence_returns_evidence(self, intelligence_alpha):
        service = EvidenceCollectorService()
        evidence = service.collect_evidence(intelligence_alpha)
        assert isinstance(evidence, list)
        assert len(evidence) > 0


class TestDecisionPlanningService:

    def test_plan_decisions_returns_priorities(self, intelligence_alpha, mock_llm):
        summary = ContextBuilderService(llm_service=mock_llm).build_context(intelligence_alpha)
        evidence = EvidenceCollectorService().collect_evidence(intelligence_alpha)

        service = DecisionPlanningService(llm_service=mock_llm)
        priorities = service.plan_decisions(intelligence_alpha, summary, evidence)
        assert isinstance(priorities, list)
        assert len(priorities) > 0


class TestRiskAssessmentService:

    def test_assess_risks_returns_categorized_risks(self, intelligence_alpha, mock_llm):
        service = RiskAssessmentService(llm_service=mock_llm)
        risks = service.assess_risks(intelligence_alpha)
        assert isinstance(risks, list)
        assert len(risks) > 0
        assert all(isinstance(r, CategorizedRisk) for r in risks)


class TestMitigationPlanningService:

    def test_plan_mitigations_returns_mitigation_plans(self, intelligence_alpha, mock_llm):
        risks = RiskAssessmentService(llm_service=mock_llm).assess_risks(intelligence_alpha)
        service = MitigationPlanningService(llm_service=mock_llm)

        mitigations = service.plan_mitigations(risks)
        assert isinstance(mitigations, list)
        assert len(mitigations) == len(risks)
        assert all(isinstance(m, MitigationPlan) for m in mitigations)


class TestReflectionService:

    def test_reflect_passes_valid_mitigations(self, intelligence_alpha, mock_llm):
        summary = ContextBuilderService(llm_service=mock_llm).build_context(intelligence_alpha)
        risks = RiskAssessmentService(llm_service=mock_llm).assess_risks(intelligence_alpha)
        mitigations = MitigationPlanningService(llm_service=mock_llm).plan_mitigations(risks)

        service = ReflectionService(llm_service=mock_llm)
        feedback = service.reflect(summary, risks, mitigations, retry_count=0)
        assert isinstance(feedback, ReflectionFeedback)
        assert feedback.passed is True
        assert feedback.grounding_score >= 0.8

    def test_reflect_triggers_retry_on_forced_flag(self, mock_llm):
        service = ReflectionService(llm_service=mock_llm)
        feedback = service.reflect(
            context_summary="FORCE_REFLECTION_RETRY test summary",
            risks=[],
            mitigations=[],
            retry_count=0,
        )
        assert feedback.passed is False


class TestRiskReportBuilderService:

    def test_build_report_returns_risk_assessment_report(self, intelligence_alpha, mock_llm):
        summary = ContextBuilderService(llm_service=mock_llm).build_context(intelligence_alpha)
        evidence = EvidenceCollectorService().collect_evidence(intelligence_alpha)
        risks = RiskAssessmentService(llm_service=mock_llm).assess_risks(intelligence_alpha)
        mitigations = MitigationPlanningService(llm_service=mock_llm).plan_mitigations(risks)
        feedback = ReflectionService(llm_service=mock_llm).reflect(summary, risks, mitigations)

        service = RiskReportBuilderService(llm_service=mock_llm)
        report = service.build_report(
            intelligence_alpha, summary, risks, evidence, mitigations, feedback
        )

        assert isinstance(report, RiskAssessmentReport)
        assert report.project_id == "PROG-ALPHA-2026"
        assert len(report.categorized_risks) > 0
        assert len(report.mitigations) > 0
